### PR TITLE
easter duck

### PR DESCRIPTION
**Pull request by benibela**
ducks

### CODE REVIEW

**Comment by ghost** [comment]
Thank you very much! A really nice idea - Easter duck on Christmas Eve :)

Would you mind if I would rename keyword `easterbasket` to simply `easter`? (I tried for short keyword in the rest of the package)

**Comment by benibela** [comment]
The naming is up to you, but `easter` could also be an abbreviation for `bunny,easterbucket`

Or `easterbucket` could be made an abbreviation for `easter,bucket` with `easter`=eggs and `bucket`=just the bucket (hard to split it with a part of the bucket in front and one behind the eggs)

**Comment by ghost** [comment]
@benibela making the (empty) bucket a separate shape might actually be doable - I am currently experimenting a bit with `\clip` in order to add the eggs on top.

I also made the colours of the eggs customisable.

**Comment by ghost** [comment]
Please check https://github.com/samcarter8/tikzducks/commit/0d755dee1a557c5b17093873a9b7d808ab1ee769 

I modified the basket shape a bit and added an handle. The basket is now also available as separate shape.

test

**Comment by benibela** [comment]
The handle looks nice

**Comment by ghost** [comment]
@benibela Thanks again for the nice idea. And also for making me aware of the usage of tikzducks in TXS - I really like the idea of having an Easter duck as one of the Easter eggs :)

However this lead to a conflict of interests and I had to edit my answer https://tex.stackexchange.com/a/332365/36296 :) With tikzducks as Easter eggs I simply can no longer advocate to change them to something else :)

**Comment by benibela** [comment]
The time has come

 I moved the eggs down a little, so you cannot see the bottom of the green one

```
\ifduck@easter
  \begin{scope}
    \clip [start angle=180, end angle=0, x radius=0.3, y radius=0.45] (0.7,0.6) arc  -- cycle [start angle=180, end angle=360, x radius=0.3, y radius=0.07] (0.7,0.6) arc  -- cycle;  
    \fill[\duck@eggb, rotate=-5]  (0.95,0.72) ellipse (0.09 and 0.13);
    \fill[\duck@egga, rotate=10]  (0.94,0.42) ellipse (0.09 and 0.13);
    \fill[\duck@eggc, rotate=-30] (0.7,1.08) ellipse (0.09 and 0.13);
  \end{scope}  
\fi%

```

**Comment by ghost** [comment]
@benibela Thanks for your suggestion! I incorporated it into the package. 

Wish you a happy Easter!

**Pull request merged**
