### PR TITLE
Support for ConTeXt Mark IV (LuaTeX / LuaMetaTeX)

### PR DESCRIPTION
**Pull request by ghost**
I've written a (sort of) wrapper so `tikzducks` it's usable as third-party module from ConTeXt MkIV. I've also made minor modifications so only TikZ generic macros are used both for LaTeX and ConTeXt (`tikzducks-generic.tex`). Not tested with Plain TeX.

I'm not sure about Overleaf color (ConTeXt uses another color scheme) nor `\scalebox` (ConTeXt uses `\scale` with different syntax, instead), so further additions are a must.

### CODE REVIEW

**Comment by samcarter** [comment]
@JairoAdelRio  Thanks a lot for your PR, that's really a great idea! I'm not at all familiar with context myself, would you maybe be able to show me a short test document for testing, which I could also show in the documentation? Something like

```
\documentclass{standalone}
\usepackage{tikzducks}

\begin{document}
	
\begin{tikzpicture}
	\duck
\end{tikzpicture}	
	
\end{document}
```

just for context? That would be very helpful!

**Comment by ghost** [comment]
Yep, of course!
```
\usemodule[tikzducks]
\usecolors[xwi] % Predefine most colors used by tikzducks
\starttext
\startcolumns[n=3]
\starttikzpicture
\duck[davidlikespineapplepizza]
\stoptikzpicture

\dorecurse{19}{

\starttikzpicture
\randuck
\stoptikzpicture

}
\stopcolumns
\stoptext
```
I forgot to comment that colors are to be defined first in ConTeXt, via `\usecolors[colorscheme]` or manually by the user. Otherwise `\randuck` won't work. :)

**Comment by samcarter** [comment]
@JairoAdelRio Thanks again for this great PR, I just merged it into the package, added it to the documentation etc.

**Comment by ghost** [comment]
Thanks to you, @samcarter 
Although the TikZ user base in ConTeXt is relatively smaller, it's nice to have this kind of goodies available. Ducks rock! :D

**Comment by samcarter** [comment]
> Ducks rock! :D

Ducks swim! :)

**Pull request merged**
